before:
  hooks:
    - go mod download

builds:
  - id: job
    main: cmd/job/main.go
    binary: executor_job_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: &env
      - CGO_ENABLED=0
    goos: &goos
      - linux
      - darwin
    goarch: &goarch
      - amd64
      - arm64
    goarm: &goarm
      - 7
  - id: snippet
    main: cmd/snippet/main.go
    binary: executor_snippet_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
snapshot:
  name_template: 'v{{ .Version }}'


release:
  # If set to true, will not auto-publish the release.
  draft: false
  prerelease: auto

  # Add extra pre-existing files to the release.
  # - build plugin index.yaml
  extra_files:
    - glob: ./plugins-index.yaml
